// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExpInstanceReset
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidResetVSExpInstanceCommandPackageString = "0440cf56-007c-45c1-aeba-ae8ca81fd5fa";
        public const string guidResetVSExpInstanceCommandPackageCmdSetString = "2ef51c7c-6cb4-45ff-823d-6ec9d8bea21d";
        public const string guidCmdIconString = "0a66e187-72de-4ae7-a0f8-3131e1cdba68";
        public static Guid guidResetVSExpInstanceCommandPackage = new Guid(guidResetVSExpInstanceCommandPackageString);
        public static Guid guidResetVSExpInstanceCommandPackageCmdSet = new Guid(guidResetVSExpInstanceCommandPackageCmdSetString);
        public static Guid guidCmdIcon = new Guid(guidCmdIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ResetVSExpInstanceCommandId = 0x0100;
        public const int bmpCmdIcon = 0x0001;
    }
}
